services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "4000:4000"
    env_file:
      - .env
    volumes:                # Mount source for live code changes without rebuild
      - .:/app
      - /app/node_modules
    depends_on:
      - redis
      - postgres

  worker:
    build:
      context: .
      dockerfile: Dockerfile
    command: ["node", "workers/videoProcessor.js"]
    env_file:
      - .env
    volumes:               # Mount source for live code changes without rebuild
      - .:/app
      - /app/node_modules 
    depends_on:
      - redis
      - postgres

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    # volumes:
    #   - redis_data:/data

  postgres:
    image: postgres:alpine
    environment:
      POSTGRES_DB: Wavelength
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres552
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  # redis_data:
  postgres_data:
